import flet as ft

def main(page: ft.Page):
    page.title = "Neustart"
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    
    page.add(
        ft.Text("🚀 ES FUNKTIONIERT!", size=35, color="green", weight="bold"),
        ft.Text("Die GitHub-Verbindung steht perfekt.", size=20)
    )

ft.app(main)
